# -*- coding: utf-8 -*-
"""pandas_table_to_graph_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uiKcBIQ776Vs_5b-FO1wg-ov3RVrqAQS
"""

import pandas as pd
from pandas.core.indexes.base import Index
import matplotlib.pyplot as plt

frequency=[100,500,1000,1500,2000,3000,4000,6000,8000,12000,15000,20000,25000]
frequency_log=[2,2.698,3,3.176,3.301,3.477,3.602,3.778,3.903,4.079,4.176,4.301,4.397]
voltage=[5,5,5,5,4.2,3.5,2.8,2,1.6,1.1,0.9,0.7,0]
index=range(1,13)
new_df=pd.DataFrame({"Frequency(f) Hz":frequency,"logf":frequency_log,"Voltage":voltage},
                      columns=["Frequency(f) Hz","logf","Voltage"])
index = pd.Index(range(1, 14,1))
new_df = new_df.set_index(index)

new_df

new_df.plot(x="logf",y="Voltage",kind="line",marker="o")
plt.title("Voltage vs Frequency in  low pass filter-->")
plt.xlabel("Frequency (logf)")
plt.ylabel("Voltage")
plt.grid()

frequency=[100,500,1000,1500,2000,3000,5000,10000,15000,20000,25000]
frequency_log=[2,2.698,3,3.176,3.301,3.477,3.698,4,4.176,4.301,4.397]
voltage=[0,0.9,1.6,1.9,2.1,2.5,2.7,2.7,2.7,2.7,2.7]
index=range(1,13)
new_df=pd.DataFrame({"Frequency(f) Hz":frequency,"logf":frequency_log,"Voltage":voltage},
                      columns=["Frequency(f) Hz","logf","Voltage"])
index = pd.Index(range(1, 12,1))
new_df = new_df.set_index(index)

new_df

new_df.plot(x="logf",y="Voltage",kind="line",marker="o")
plt.title("Voltage vs Frequency in  High pass filter-->")
plt.xlabel("Frequency (logf)")
plt.ylabel("Voltage")
plt.grid()